In [1]:
import pandas as pd
import numpy as np
data=pd.read_csv("adult22.csv")
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27651 entries, 0 to 27650
Columns: 637 entries, URBRRL to POVRATTC_A
dtypes: float64(399), int64(237), object(1)
memory usage: 134.4+ MB


In [2]:
mental_health ="URBRRL, REGION, SEX_A, AGEP_A, HISPALLP_A, EDUCP_A, PHSTAT_A, HYPEV_A, CHLEV_A, CHDEV_A, ASEV_A, CANEV_A, DIBEV_A, DIBTYPE_A, COPDEV_A, ARTHEV_A, DEMENEV_A, ANXEV_A,DEPEV_A, CFSEV_A, MEDRXTRT_A, HLTHCOND_A, EPIEV_A, BMICAT_A, VISIONDF_A, HEARINGDF_A, DIFF_A, COMDIFF_A, SOCWRKLIM_A, CVDDIAG_A, MHTHRPY_A, MHTHND_A, MHTHDLY_A,SMKCIGST_A, SMKECIGST_A, CIGAREV_A, DRKSTAT_A, SLPHOURS_A, MEDITATE_A, ORIENT_A, MARSTAT_A, PARSTAT_A, EMPWRKFT1_A"
mental_health_list = [attr.strip() for attr in mental_health.split(",")]

In [3]:
healthcare_access ="URBRRL, REGION, SEX_A, AGEP_A, HISPALLP_A, EDUCP_A, PHSTAT_A, HYPEV_A, CHLEV_A, CHDEV_A, ASEV_A, CANEV_A, DIBEV_A, DIBTYPE_A, COPDEV_A, ARTHEV_A, DEMENEV_A, CFSEV_A, MEDRXTRT_A, HLTHCOND_A, EPIEV_A, BMICAT_A, VISIONDF_A, HEARINGDF_A, DIFF_A, COMDIFF_A, SOCWRKLIM_A, CVDDIAG_A, MHTHND_A, MHTHDLY_A, SMKCIGST_A, SMKECIGST_A, CIGAREV_A, DRKSTAT_A,  ORIENT_A, MARSTAT_A, PARSTAT_A, EMPWRKFT1_A, EMPHEALINS_A, RATCAT_A, TRANSPOR_A, NOTCOV_A, HICOV_A, LASTDR_A, USUALPL_A, URGNT12MTC_A, EMERG12MTC_A, MEDDL12M_A, MEDNG12M_A, ABINSUR_A, ABAVAIL_A, ABOPEN_A, ABTOOLONG_A, ABTIME_A, RXSK12M_A, RXLS12M_A, RXDL12M_A, RXDG12M_A,PAYBLL12M_A, PAYWORRY_A, HISTOPMISS_A, HISTOPAGE_A, HISTOPCOST_A, HISTOPELIG_A, RSNHICOST_A, RSNHIWANT_A, RSNHIELIG_A, RSNHICONF_A, RSNHIMEET_A, RSNHIWAIT_A, RSNHIOTH_A"
healthcare_access_list = [attr.strip() for attr in healthcare_access.split(",")]

In [4]:
mh_data=data[mental_health_list]
ha_data=data[healthcare_access_list]

In [5]:
mh_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27651 entries, 0 to 27650
Data columns (total 43 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   URBRRL       27651 non-null  int64  
 1   REGION       27651 non-null  int64  
 2   SEX_A        27651 non-null  int64  
 3   AGEP_A       27651 non-null  int64  
 4   HISPALLP_A   27651 non-null  int64  
 5   EDUCP_A      27651 non-null  int64  
 6   PHSTAT_A     27651 non-null  int64  
 7   HYPEV_A      27651 non-null  int64  
 8   CHLEV_A      27651 non-null  int64  
 9   CHDEV_A      27651 non-null  int64  
 10  ASEV_A       27651 non-null  int64  
 11  CANEV_A      27651 non-null  int64  
 12  DIBEV_A      27651 non-null  int64  
 13  DIBTYPE_A    2946 non-null   float64
 14  COPDEV_A     27651 non-null  int64  
 15  ARTHEV_A     27651 non-null  int64  
 16  DEMENEV_A    27651 non-null  int64  
 17  ANXEV_A      27651 non-null  int64  
 18  DEPEV_A      27651 non-null  int64  
 19  CFSE

In [6]:
ha_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27651 entries, 0 to 27650
Data columns (total 71 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   URBRRL        27651 non-null  int64  
 1   REGION        27651 non-null  int64  
 2   SEX_A         27651 non-null  int64  
 3   AGEP_A        27651 non-null  int64  
 4   HISPALLP_A    27651 non-null  int64  
 5   EDUCP_A       27651 non-null  int64  
 6   PHSTAT_A      27651 non-null  int64  
 7   HYPEV_A       27651 non-null  int64  
 8   CHLEV_A       27651 non-null  int64  
 9   CHDEV_A       27651 non-null  int64  
 10  ASEV_A        27651 non-null  int64  
 11  CANEV_A       27651 non-null  int64  
 12  DIBEV_A       27651 non-null  int64  
 13  DIBTYPE_A     2946 non-null   float64
 14  COPDEV_A      27651 non-null  int64  
 15  ARTHEV_A      27651 non-null  int64  
 16  DEMENEV_A     27651 non-null  int64  
 17  CFSEV_A       27651 non-null  int64  
 18  MEDRXTRT_A    27651 non-nu

In [7]:
missing_columns = mh_data.columns[mh_data.isnull().any()]
missing_data = mh_data[missing_columns].isnull().sum()

print("Columns with Missing Values:")
print(missing_data)

Columns with Missing Values:
DIBTYPE_A      24705
EMPWRKFT1_A    12297
dtype: int64


In [8]:
# assert(np.isnan(mh_data[mh_data['DIBEV_A'] != 1]['DIBTYPE_A'].to_numpy()).all())
# assert(not np.isnan(mh_data[mh_data['DIBEV_A'] == 1]['DIBTYPE_A'].to_numpy()).any())
mh_data['DIBTYPE_A'].fillna(-1, inplace=True, downcast='infer')
print(mh_data['DIBTYPE_A'].isnull().sum(), end=" ")
mh_data['EMPWRKFT1_A'].fillna(-1, inplace=True, downcast='infer')
print(mh_data['EMPWRKFT1_A'].isnull().sum())

0 0


<ipython-input-8-33d9b436c436>:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  mh_data['DIBTYPE_A'].fillna(-1, inplace=True, downcast='infer')
<ipython-input-8-33d9b436c436>:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  mh_data['EMPWRKFT1_A'].fillna(-1, inplace=True, downcast='infer')


In [9]:
lambdas = [
  lambda x: True,
  lambda x: True,
  lambda x: 'mode' if x not in [1,2] else True,
  lambda x: 'mean' if x in [97,98,99] else True,
  lambda x: True,
  lambda x: 'mode' if x in [97,98,99] else True,
  lambda x: 'mode' if x not in [1,2,3,4,5] else True,
  lambda x: 'mode' if x not in [1,2] else True,
  lambda x: 'mode' if x not in [1,2] else True,
  lambda x: 'mode' if x not in [1,2] else True,
  lambda x: 'mode' if x not in [1,2] else True,
  lambda x: 'mode' if x not in [1,2] else True,
  lambda x: 'mode' if x not in [1,2] else True,
  lambda x: 'mode' if x not in [-1,1,2,3] else True,
  lambda x: 'mode' if x not in [1,2] else True,
  lambda x: 'mode' if x not in [1,2] else True,
  lambda x: 'mode' if x not in [1,2] else True,
  lambda x: 'mode' if x not in [1,2] else True,
  lambda x: 'mode' if x not in [1,2] else True,
  lambda x: 'mode' if x not in [1,2] else True,
  lambda x: 'mode' if x not in [1,2] else True,
  lambda x: 'mode' if x not in [1,2] else True,
  lambda x: 'mode' if x not in [1,2] else True,
  lambda x: 'mode' if x not in [1,2,3,4] else True,
  lambda x: 'mode' if x not in [1,2,3,4] else True,
  lambda x: 'mode' if x not in [1,2,3,4] else True,
  lambda x: 'mode' if x not in [1,2,3,4] else True,
  lambda x: 'mode' if x not in [1,2,3,4] else True,
  lambda x: 'mode' if x not in [1,2] else True,
  lambda x: 'mode' if x not in [1,2] else True,
  lambda x: 'mode' if x not in [1,2] else True,
  lambda x: 'mode' if x not in [1,2] else True,
  lambda x: 'mode' if x not in [1,2] else True,
  lambda x: 'mode' if x not in [1,2,3,4] else True,
  lambda x: 'mode' if x not in [1,2,3] else True,
  lambda x: 'mode' if x not in [1,2] else True,
  lambda x: 'mode' if x in [10] else True,
  lambda x: 'mean' if x in [97,98,99] else True,
  lambda x: 'mode' if x not in [1,2] else True,
  lambda x: 'mode' if x not in [1,2,3,4] else True,
  lambda x: 'mode' if x in [9] else True,
  lambda x: 'mode' if x not in [1,2,3] else True,
  lambda x: 'mode' if x not in [-1,1,2] else True
]

In [10]:
def replace_values_with_custom_functions(df, custom_functions_list):
    for idx, column_name in enumerate(df.columns):
        # print(len(df.columns), len(custom_functions_list), idx)
        custom_function = custom_functions_list[idx]
        if column_name == "SLPHOURS_A":
            mean_value = df[(df[column_name] >= 1) & (df[column_name] <= 24)][column_name].mean()
            std_dev = df[(df[column_name] >= 1) & (df[column_name] <= 24)][column_name].to_numpy().std()
            random_sample = np.random.default_rng().normal(loc=mean_value, scale=std_dev, size=1)
        if column_name == "AGEP_A":
            mean_value = df[(df[column_name] >= 18) & (df[column_name] <= 85)][column_name].mean()
            std_dev = df[(df[column_name] >= 18) & (df[column_name] <= 85)][column_name].to_numpy().std()
            random_sample = np.random.default_rng().normal(loc=mean_value, scale=std_dev, size=1)
        mode_value = df[column_name].mode()[0]
        def apply_custom_function(x):
            result = custom_function(x)
            if result is True:
                return x
            elif result == 'mode':
                return mode_value
            elif result == 'mean':
                return random_sample
            else:
                return result

        original_column = df[column_name].copy()
        df[column_name] = df[column_name].apply(apply_custom_function)

        num_rows_replaced = (original_column != df[column_name]).sum()
        # print(f"Replaced {num_rows_replaced} rows in column '{column_name}' based on the given custom function.")
replace_values_with_custom_functions(mh_data, lambdas)

<ipython-input-10-2783a2bf70e0>:26: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[column_name] = df[column_name].apply(apply_custom_function)
<ipython-input-10-2783a2bf70e0>:26: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[column_name] = df[column_name].apply(apply_custom_function)
<ipython-input-10-2783a2bf70e0>:26: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation:

In [11]:
missing_columns = ha_data.columns[ha_data.isnull().any()]
missing_data = ha_data[missing_columns].isnull().sum()

print("Columns with Missing Values:")
print(missing_data)

Columns with Missing Values:
DIBTYPE_A       24705
EMPWRKFT1_A     12297
EMPHEALINS_A    10923
RXSK12M_A        7992
RXLS12M_A        7992
RXDL12M_A        7992
HISTOPMISS_A    26688
HISTOPAGE_A     26688
HISTOPCOST_A    26688
HISTOPELIG_A    26688
RSNHICOST_A     25595
RSNHIWANT_A     25595
RSNHIELIG_A     25595
RSNHICONF_A     25595
RSNHIMEET_A     25595
RSNHIWAIT_A     25595
RSNHIOTH_A      25595
dtype: int64


In [12]:
temp = "HISTOPMISS_A, HISTOPAGE_A, HISTOPCOST_A, HISTOPELIG_A, RSNHICOST_A, RSNHIWANT_A, RSNHIELIG_A, RSNHICONF_A, RSNHIMEET_A, RSNHIWAIT_A, RSNHIOTH_A"
reason_list = [attr.strip() for attr in temp.split(",")]
reason_data=ha_data[reason_list]
ha_data["NO_HC_REASON"] = reason_data.apply(lambda row: row.index[row == 1][0] if 1 in row.values else None, axis=1)
print(ha_data["NO_HC_REASON"].unique())
ha_data['NO_HC_REASON'].fillna("INSURED", inplace=True,downcast='infer')
print(ha_data["NO_HC_REASON"].isna().sum())
ha_data=ha_data.drop(columns=reason_list)

[None 'RSNHIWANT_A' 'HISTOPMISS_A' 'RSNHICOST_A' 'HISTOPAGE_A'
 'RSNHICONF_A' 'RSNHIWAIT_A' 'HISTOPELIG_A' 'HISTOPCOST_A' 'RSNHIOTH_A'
 'RSNHIELIG_A' 'RSNHIMEET_A']
0


<ipython-input-12-2e84fe398f19>:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ha_data["NO_HC_REASON"] = reason_data.apply(lambda row: row.index[row == 1][0] if 1 in row.values else None, axis=1)
<ipython-input-12-2e84fe398f19>:6: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ha_data['NO_HC_REASON'].fillna("INSURED", inplace=True,downcast='infer')


In [13]:
print(np.isnan(ha_data[ha_data['DIBEV_A'] == 1]['DIBTYPE_A'].to_numpy()).sum(), ha_data[ha_data['DIBEV_A'] == 1]['DIBTYPE_A'].size)
ha_data['DIBTYPE_A'].fillna(-1, inplace=True,downcast='infer')
print(ha_data['DIBTYPE_A'].isnull().sum(), end=" ")
ha_data['EMPWRKFT1_A'].fillna(-1, inplace=True,downcast='infer')
print(ha_data['EMPWRKFT1_A'].isnull().sum(), end=" ")
ha_data['EMPHEALINS_A'].fillna(-1, inplace=True,downcast='infer')
print(ha_data['EMPHEALINS_A'].isnull().sum(), end=" ")
ha_data['RXSK12M_A'].fillna(-1, inplace=True,downcast='infer')
print(ha_data['RXSK12M_A'].isnull().sum(), end=" ")
ha_data['RXLS12M_A'].fillna(-1, inplace=True,downcast='infer')
print(ha_data['RXLS12M_A'].isnull().sum(), end=" ")
ha_data['RXDL12M_A'].fillna(-1, inplace=True,downcast='infer')
print(ha_data['RXDL12M_A'].isnull().sum(), end=" ")

0 2946
0 0 0 0 0 0 

In [14]:
lambdas = [
    lambda x: True, lambda x: True, lambda x: 'mode' if x not in [1,2] else True, lambda x: 'mean' if x in [97,98,99] else True, lambda x: True, lambda x: 'mode' if x in [97,98,99] else True,
    lambda x: 'mode' if x not in [1,2,3,4,5] else True, lambda x: 'mode' if x not in [1,2] else True, lambda x: 'mode' if x not in [1,2] else True, lambda x: 'mode' if x not in [1,2] else True,
    lambda x: 'mode' if x not in [1,2] else True, lambda x: 'mode' if x not in [1,2] else True, lambda x: 'mode' if x not in [1,2] else True, lambda x: 'mode' if x not in [-1,1,2,3] else True,
    lambda x: 'mode' if x not in [1,2] else True, lambda x: 'mode' if x not in [1,2] else True, lambda x: 'mode' if x not in [1,2] else True, lambda x: 'mode' if x not in [1,2] else True,
    lambda x: 'mode' if x not in [1,2] else True, lambda x: 'mode' if x not in [1,2] else True, lambda x: 'mode' if x not in [1,2] else True, lambda x: 'mode' if x not in [1,2,3,4] else True,
    lambda x: 'mode' if x not in [1,2,3,4] else True, lambda x: 'mode' if x not in [1,2,3,4] else True, lambda x: 'mode' if x not in [1,2,3,4] else True,
    lambda x: 'mode' if x not in [1,2,3,4] else True, lambda x: 'mode' if x not in [1,2] else True, lambda x: 'mode' if x not in [1,2] else True, lambda x: 'mode' if x not in [1,2] else True,
    lambda x: 'mode' if x not in [1,2] else True, lambda x: 'mode' if x not in [1,2,3,4] else True, lambda x: 'mode' if x not in [1,2,3] else True, lambda x: 'mode' if x not in [1,2] else True,
    lambda x: 'mode' if x in [10] else True, lambda x: 'mode' if x not in [1,2,3,4] else True, lambda x: 'mode' if x in [9] else True, lambda x: 'mode' if x not in [1,2,3] else True,
    lambda x: 'mode' if x not in [-1,1,2] else True, lambda x: 'mode' if x not in [-1,1,2] else True, lambda x: 'mode' if x in [98] else True, lambda x: 'mode' if x not in [1,2] else True,
    lambda x: 'mode' if x not in [1,2] else True, lambda x: 'mode' if x not in [1,2] else True, lambda x: 'mode' if x in [7,8,9] else True, lambda x: 'mode' if x not in [1,2,3] else True,
    lambda x: 'mode' if x in [7,8,9] else True, lambda x: 'mode' if x in [7,8,9] else True, lambda x: 'mode' if x not in [1,2] else True, lambda x: 'mode' if x not in [1,2] else True,
    lambda x: 'mode' if x not in [1,2] else True, lambda x: 'mode' if x not in [1,2] else True, lambda x: 'mode' if x not in [1,2] else True, lambda x: 'mode' if x not in [1,2] else True,
    lambda x: 'mode' if x not in [1,2] else True, lambda x: 'mode' if x not in [-1,1,2] else True, lambda x: 'mode' if x not in [-1,1,2] else True, lambda x: 'mode' if x not in [-1,1,2] else True,
    lambda x: 'mode' if x not in [1,2] else True, lambda x: 'mode' if x not in [1,2] else True, lambda x: 'mode' if x not in [1,2,3] else True, lambda x: True
]

In [15]:
def replace_values_with_custom_functions(df, custom_functions_list):
    for idx, column_name in enumerate(df.columns):
        # print(len(df.columns), len(custom_functions_list), idx)
        custom_function = custom_functions_list[idx]
        if column_name == "AGEP_A":
            mean_value = df[(df[column_name] >= 18) & (df[column_name] <= 85)][column_name].mean()
            std_dev = df[(df[column_name] >= 18) & (df[column_name] <= 85)][column_name].to_numpy().std()
            random_sample = np.random.default_rng().normal(loc=mean_value, scale=std_dev, size=1)
        mode_value = df[column_name].mode()[0]
        def apply_custom_function(x):
            result = custom_function(x)
            if result is True:
                return x
            elif result == 'mode':
                return mode_value
            elif result == 'mean':
                return random_sample
            else:
                return result

        original_column = df[column_name].copy()
        df[column_name] = df[column_name].apply(apply_custom_function)

        num_rows_replaced = (original_column != df[column_name]).sum()
        # print(f"Replaced {num_rows_replaced} rows in column '{column_name}' based on the given custom function.")
replace_values_with_custom_functions(ha_data, lambdas)

In [16]:
# Creating the target variable for both the tasks
mh_data['Y'] = (mh_data['ANXEV_A'] == 1) | (mh_data['DEPEV_A'] == 1)
for i in range(len(mh_data['Y'])):
  if mh_data['Y'][i]:
    mh_data['Y'][i] = 1
  else:
    mh_data['Y'][i] = 0
print(mh_data['Y'].unique())
mh_data.drop(['ANXEV_A', 'DEPEV_A'], axis=1, inplace=True)

<ipython-input-16-de3aebcd57f7>:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  mh_data['Y'] = (mh_data['ANXEV_A'] == 1) | (mh_data['DEPEV_A'] == 1)
<ipython-input-16-de3aebcd57f7>:7: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  mh_data['Y'][i] = 0
<ipython-input-16-de3aebcd57f7>:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  mh_data['Y'][i] = 1


[0 1]


<ipython-input-16-de3aebcd57f7>:9: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  mh_data.drop(['ANXEV_A', 'DEPEV_A'], axis=1, inplace=True)


In [17]:
ha_data['Y'] = (ha_data['ABINSUR_A'] == 1) | (ha_data['ABAVAIL_A'] == 1) | (ha_data['ABOPEN_A'] == 1) | (ha_data['ABTOOLONG_A'] == 1) | (ha_data['ABTIME_A'] == 1)
for i in range(len(ha_data['Y'])):
  if ha_data['Y'][i]:
    ha_data['Y'][i] = 1
  else:
    ha_data['Y'][i] = 0
print(ha_data['Y'].unique())
ha_data.drop(['ABINSUR_A', 'ABAVAIL_A', 'ABOPEN_A', 'ABTOOLONG_A', 'ABTIME_A'], axis=1, inplace=True)

<ipython-input-17-8df3fe48c50f>:6: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ha_data['Y'][i] = 0


[0 1]


In [18]:
mh_data.to_csv("mh_data.csv")
ha_data.to_csv("ha_data.csv")

In [19]:
mh_remove="MHTHRPY_A, MHTHND_A, MHTHDLY_A"
mh_remove_list = [attr.strip() for attr in mh_remove.split(",")]
mh_data=mh_data.drop(columns=mh_remove_list)

In [20]:
Categorical='URBRRL, REGION, HISPALLP_A, EDUCP_A, PHSTAT_A, DIBTYPE_A, BMICAT_A, VISIONDF_A, HEARINGDF_A, DIFF_A, COMDIFF_A, SMKCIGST_A, SMKECIGST_A, DRKSTAT_A, ORIENT_A, MARSTAT_A, PARSTAT_A, EMPWRKFT1_A'
cat_list=[attr.strip() for attr in Categorical.split(",")]
mh_data = pd.get_dummies(mh_data,columns=cat_list)
mh_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27651 entries, 0 to 27650
Columns: 109 entries, SEX_A to EMPWRKFT1_A_2
dtypes: int64(18), object(3), uint8(88)
memory usage: 6.8+ MB


In [21]:
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import f1_score, precision_score, recall_score
from sklearn.preprocessing import MinMaxScaler, StandardScaler
from sklearn.impute import KNNImputer
from sklearn.feature_selection import SelectPercentile,chi2
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import mutual_info_classif
from sklearn.model_selection import KFold
from sklearn.linear_model import LogisticRegression
%matplotlib inline
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.svm import SVC

In [22]:
X = mh_data.drop('Y', axis=1)
y = mh_data['Y'].astype('int')

In [23]:
min_max_scaler = MinMaxScaler()
X_normalized = min_max_scaler.fit_transform(X)
standard_scaler = StandardScaler()
X_standardized = standard_scaler.fit_transform(X_normalized)

In [24]:
X_train, X_test, y_train, y_test = train_test_split(X_standardized, y, test_size=0.3, random_state=42)

In [25]:
model = LogisticRegression(random_state=42)
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
classification_rep = classification_report(y_test, y_pred)

print(f"Accuracy: {accuracy:.2f}")
print("Confusion Matrix:")
print(conf_matrix)
print("Classification Report:")
print(classification_rep)

Accuracy: 0.80
Confusion Matrix:
[[5949  292]
 [1383  672]]
Classification Report:
              precision    recall  f1-score   support

           0       0.81      0.95      0.88      6241
           1       0.70      0.33      0.45      2055

    accuracy                           0.80      8296
   macro avg       0.75      0.64      0.66      8296
weighted avg       0.78      0.80      0.77      8296



In [26]:
model = SVC(kernel='linear', C=1, random_state=42)
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
classification_rep = classification_report(y_test, y_pred)

print(f"Accuracy: {accuracy:.2f}")
print("Confusion Matrix:")
print(conf_matrix)
print("Classification Report:")
print(classification_rep)

Accuracy: 0.78
Confusion Matrix:
[[6096  145]
 [1714  341]]
Classification Report:
              precision    recall  f1-score   support

           0       0.78      0.98      0.87      6241
           1       0.70      0.17      0.27      2055

    accuracy                           0.78      8296
   macro avg       0.74      0.57      0.57      8296
weighted avg       0.76      0.78      0.72      8296



In [27]:
model = RandomForestClassifier(n_estimators=100, random_state=42)
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
classification_rep = classification_report(y_test, y_pred)

print(f"Accuracy: {accuracy:.2f}")
print("Confusion Matrix:")
print(conf_matrix)
print("Classification Report:")
print(classification_rep)

Accuracy: 0.79
Confusion Matrix:
[[6028  213]
 [1560  495]]
Classification Report:
              precision    recall  f1-score   support

           0       0.79      0.97      0.87      6241
           1       0.70      0.24      0.36      2055

    accuracy                           0.79      8296
   macro avg       0.75      0.60      0.62      8296
weighted avg       0.77      0.79      0.74      8296



In [28]:
Categorical_ha='URBRRL, REGION, HISPALLP_A, EDUCP_A, PHSTAT_A, DIBTYPE_A, BMICAT_A, VISIONDF_A, HEARINGDF_A, DIFF_A, COMDIFF_A, SMKCIGST_A, SMKECIGST_A, DRKSTAT_A,  ORIENT_A, MARSTAT_A, PARSTAT_A, EMPWRKFT1_A, EMPHEALINS_A, RATCAT_A, LASTDR_A, USUALPL_A, URGNT12MTC_A, EMERG12MTC_A, RXSK12M_A, RXLS12M_A, RXDL12M_A, PAYWORRY_A, NO_HC_REASON'
cat_list_ha=[attr.strip() for attr in Categorical_ha.split(",")]
ha_data = pd.get_dummies(ha_data,columns=cat_list_ha)
ha_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27651 entries, 0 to 27650
Columns: 178 entries, SEX_A to NO_HC_REASON_RSNHIWANT_A
dtypes: int64(26), object(2), uint8(150)
memory usage: 9.9+ MB


In [29]:
X = ha_data.drop('Y', axis=1)
y = ha_data['Y'].astype('int')

In [30]:
min_max_scaler = MinMaxScaler()
X_normalized = min_max_scaler.fit_transform(X)
standard_scaler = StandardScaler()
X_standardized = standard_scaler.fit_transform(X_normalized)

In [31]:
X_train, X_test, y_train, y_test = train_test_split(X_standardized, y, test_size=0.3, random_state=42)

In [32]:
model = LogisticRegression(random_state=42)
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
classification_rep = classification_report(y_test, y_pred)

print(f"Accuracy: {accuracy:.2f}")
print("Confusion Matrix:")
print(conf_matrix)
print("Classification Report:")
print(classification_rep)

Accuracy: 0.80
Confusion Matrix:
[[6304  213]
 [1428  351]]
Classification Report:
              precision    recall  f1-score   support

           0       0.82      0.97      0.88      6517
           1       0.62      0.20      0.30      1779

    accuracy                           0.80      8296
   macro avg       0.72      0.58      0.59      8296
weighted avg       0.77      0.80      0.76      8296



In [33]:
model = SVC(kernel='linear', C=1, random_state=42)
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
classification_rep = classification_report(y_test, y_pred)

print(f"Accuracy: {accuracy:.2f}")
print("Confusion Matrix:")
print(conf_matrix)
print("Classification Report:")
print(classification_rep)

Accuracy: 0.79
Confusion Matrix:
[[6371  146]
 [1590  189]]
Classification Report:
              precision    recall  f1-score   support

           0       0.80      0.98      0.88      6517
           1       0.56      0.11      0.18      1779

    accuracy                           0.79      8296
   macro avg       0.68      0.54      0.53      8296
weighted avg       0.75      0.79      0.73      8296



In [34]:
model = RandomForestClassifier(n_estimators=100, random_state=42)
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
classification_rep = classification_report(y_test, y_pred)

print(f"Accuracy: {accuracy:.2f}")
print("Confusion Matrix:")
print(conf_matrix)
print("Classification Report:")
print(classification_rep)

Accuracy: 0.80
Confusion Matrix:
[[6385  132]
 [1542  237]]
Classification Report:
              precision    recall  f1-score   support

           0       0.81      0.98      0.88      6517
           1       0.64      0.13      0.22      1779

    accuracy                           0.80      8296
   macro avg       0.72      0.56      0.55      8296
weighted avg       0.77      0.80      0.74      8296

